# Generated by Django 6.1 on 2026-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show_in_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='show_in_newsdesk',
            field=models.BooleanField(default=False),
        ),
    ]
