# Generated by Django 6.1 on 2026-08-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_show_in_hero_news_show_in_newsdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
